---
.deploy_environment_modules:
  stage: deploy
  only:
    refs:
      - branches
  before_script: []
  script:
    - if [ -z "$PUPPET_ENVIRONMENT" ] ; then
    - echo 'PUPPET_ENVIRONMENT not set' >&2
    - exit 1
    - fi
    - 'sudo r10k deploy environment "$PUPPET_ENVIRONMENT" -pv'
  variables:
    GIT_STRATEGY: none
