---
.deploy_module:
  stage: deploy
  only:
    refs:
      - branches
  before_script: []
  script:
    - |
      [ -f /etc/profile.d/puppet-agent.sh ] && . /etc/profile.d/puppet-agent.sh
      if [ -z "$PUPPET_ENVIRONMENT" ] ; then
          echo 'PUPPET_ENVIRONMENT not set' >&2
          exit 1
      fi
      if [ -z "$PUPPET_MODULE" ] ; then
          echo 'PUPPET_MODULE not set' >&2
          exit 1
      fi
      if [ "$PUPPET_ENVIRONMENT" = "$DEFAULT_BRANCH" ] ; then
          echo "Deploying $PUPPET_MODULE..."
          sudo /usr/bin/r10k deploy module "$PUPPET_MODULE" -v
          for environment in /etc/puppetlabs/code/environments/* ; do
              if [ -f "$environment"/.git -a -f "$environment"/Puppetfile ] ; then
                  sudo /opt/puppetlabs/bin/puppet generate types --environment "${environment##*/}"
              fi
          done
      elif [ -d /etc/puppetlabs/code/environments/"$PUPPET_ENVIRONMENT" ] ; then
          echo "Deploying $PUPPET_MODULE in environment $PUPPET_ENVIRONMENT..."
          sudo /usr/bin/r10k deploy module "$PUPPET_MODULE" -e "$PUPPET_ENVIRONMENT" -v
          sudo /opt/puppetlabs/bin/puppet generate types --environment "$PUPPET_ENVIRONMENT"
      else
          echo "Skipping deployment of $PUPPET_MODULE in environment $PUPPET_ENVIRONMENT."
          echo "No matching environment."
      fi
  variables:
    GIT_STRATEGY: none
