---
.deploy_environment_modules:
  stage: deploy
  only:
    refs:
      - branches
  before_script: []
  script:
    - '[ -f /etc/profile.d/puppet-agent.sh ] && . /etc/profile.d/puppet-agent.sh'
    - if [ -z "$PUPPET_ENVIRONMENT" ] ; then
    - echo 'PUPPET_ENVIRONMENT not set' >&2
    - exit 1
    - fi
    - 'sudo /usr/bin/r10k deploy environment "$PUPPET_ENVIRONMENT" -pv'
    - 'sudo /opt/puppetlabs/bin/puppet generate types --environment "$PUPPET_ENVIRONMENT"'
  variables:
    GIT_STRATEGY: none
